# Basic
title: Xander
subtitle: Mr.X's blog site!
welcome_message: Love
description: 天生的，独一无二的！
creator: <a href="https://mrx520.github.io/">@mrx520</a>

url: "https://mrx520.github.io"

permalink: /:year/:month/:title/

# Format
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: red

# The blog button should not be removed.
blog_button:
    title: Mr.X
    description: Welcome to here, I love you!

# Navigation buttons in the front page.
nav:
    - {title: Projects, description: My Projects, url: 'https://github.com/mrx520'}

# Pagination
gems: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    disqus: vno-jekyll
    # duoshuo: 
    
# Social
social:
    weibo: xxxxxx
    github: mrx520
    twitter: xxxxxx
    gplus: xxxxxx
    mail: jxjy.ing@foxmail.com

# Google Analytics
ga:
    # id: your_ga_id
    # host: your_host
